version: '3.8'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3305:3305
    environment:
      MYSQL_ROOT_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9001:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password